#!/usr/bin/env bash
# Generate sw-manifest.js — the list of app-shell files the offline service worker
# precaches. crashDot has no bundler, so this globs the actual files. Run before a
# deploy (or after adding a js/synthdef/lib file) so offline stays in sync.
#   ./scripts/gen-sw-manifest.sh
set -e
cd "$(dirname "$0")/.."

OUT="sw-manifest.js"

# Enumerate the boot-critical, same-origin assets (URL paths relative to root).
{
  echo "index.html"
  echo "config.json"
  [ -f css/style.css ] && echo "css/style.css"
  find js -name '*.js' -type f
  find lib/codemirror -type f \( -name '*.js' -o -name '*.css' \)
  echo "lib/dist/supersonic.js"
  find lib/dist/wasm -name '*.wasm' -type f
  [ -f lib/yjs/yjs-bundle.js ] && echo "lib/yjs/yjs-bundle.js"
  find synthdefs/compiled -name '*.scsyndef' -type f
} | sort -u > /tmp/wfd_sw_list.txt

COUNT=$(wc -l < /tmp/wfd_sw_list.txt | tr -d ' ')

{
  echo "// AUTO-GENERATED by scripts/gen-sw-manifest.sh — do not edit by hand."
  echo "// The app-shell files the offline service worker precaches ($COUNT files)."
  echo "self.__WFD_PRECACHE = ["
  sed "s#.*#  './&',#" /tmp/wfd_sw_list.txt
  echo "];"
} > "$OUT"

rm -f /tmp/wfd_sw_list.txt
echo "Wrote $OUT with $COUNT entries."
