#!/usr/bin/env bash
# Generate sw-manifest.js — the list of app-shell files the offline service worker
# precaches. crashDot has no bundler, so this globs the actual files. Run before a
# deploy (or after adding a js/synthdef/lib file) so offline stays in sync.
#   ./scripts/gen-sw-manifest.sh           write it
#   ./scripts/gen-sw-manifest.sh --check   exit 1 if it is out of date, change nothing
#
# The --check mode exists because "run this before a deploy" is a thing you forget.
# It had been forgotten: three modules (the layers panel, the video recorder, vrand)
# were missing, so an installed PWA or an offline workshop machine simply failed to
# load them — the scenario workshop.md is written for.
set -e
cd "$(dirname "$0")/.."

OUT="sw-manifest.js"
CHECK=""
[ "$1" = "--check" ] && CHECK=1

# Enumerate the boot-critical, same-origin assets (URL paths relative to root).
{
  echo "index.html"
  [ -f visuals.html ] && echo "visuals.html"
  echo "config.json"
  [ -f manifest.webmanifest ] && echo "manifest.webmanifest"
  find icons -type f \( -name '*.png' -o -name '*.svg' \) 2>/dev/null
  [ -f css/style.css ] && echo "css/style.css"
  find js -name '*.js' -type f
  find lib/codemirror -type f \( -name '*.js' -o -name '*.css' \)
  echo "lib/dist/supersonic.js"
  [ -f lib/yjs/yjs-bundle.js ] && echo "lib/yjs/yjs-bundle.js"
  # NOTE: the WASM (lib/dist/wasm) and synthdefs/compiled are deliberately NOT
  # precached — they're fetched at BOOT (after the SW is controlling), so the
  # network-first handler caches them on use. Precaching them would force a second
  # heavy fetch that competes with the boot's own WASM/synthdef load. They become
  # available offline after the first online boot.
} | sort -u > /tmp/wfd_sw_list.txt

COUNT=$(wc -l < /tmp/wfd_sw_list.txt | tr -d ' ')

render() {
  echo "// AUTO-GENERATED by scripts/gen-sw-manifest.sh — do not edit by hand."
  echo "// The app-shell files the offline service worker precaches ($COUNT files)."
  echo "self.__WFD_PRECACHE = ["
  sed "s#.*#  './&',#" /tmp/wfd_sw_list.txt
  echo "];"
}

if [ -n "$CHECK" ]; then
  if render | diff -q - "$OUT" > /dev/null 2>&1; then
    rm -f /tmp/wfd_sw_list.txt
    echo "sw-manifest.js is up to date ($COUNT entries)."
  else
    echo "sw-manifest.js is OUT OF DATE — offline/PWA will 404 on the difference:"
    render | diff "$OUT" - | grep '^[<>]' | head -20
    rm -f /tmp/wfd_sw_list.txt
    echo "Run ./scripts/gen-sw-manifest.sh"
    exit 1
  fi
else
  render > "$OUT"
  rm -f /tmp/wfd_sw_list.txt
  echo "Wrote $OUT with $COUNT entries."
fi
